image: docker:latest

services:
  - docker:dind

stages:
  - tests

test-workstation:
  stage: tests
  script:
    - docker run -d --privileged --name fedora-ansible -v /sys/fs/cgroup:/sys/fs/cgroup:ro -v `pwd`:/ansible remyj38/fedora-ansible
    - docker exec fedora-ansible useradd -m -d /home/remy/ remy
    - docker exec fedora-ansible ansible-playbook /ansible/workstation.yml
