---
- hosts: localhost
  user: root
  tasks:
    - include_role:
        name: prerequisites

    - include_role:
        name: aria2

    - include_role:
        name: firefox
      vars:
        channel: beta-latest

    - include_role:
        name: firefox
      vars:
        install_path: /opt/firefox-developer
        channel: devedition-latest

    - include_role:
        name: megasync

    - include_role:
        name: multimedia

    - include_role:
        name: development

    - name: Install tools
      dnf:
        name:
          - aspell-fr
          - bash-completion
          - cockpit
          - cockpit-podman
          - dconf-editor
          - firewall-config
          - gconf-editor
          - gnome-tweaks
          - hplip
          - iftop
          - iotop
          - jq
          - lm_sensors
          - mutt
          - net-tools
          - nethogs
          - nmap
          - ntp
          - setools-gui
          - smartmontools
          - umit
          - usbutils
          - util-linux-user
          - vim
          - wireshark
          - zsh
        state: present

    - name: Enable cockpit
      systemd:
        name: cockpit.socket
        enabled: yes
        state: started

    - name: Install Signal repository
      get_url:
        url: https://copr.fedorainfracloud.org/coprs/luminoso/Signal-Desktop/repo/fedora-{{ hostvars[inventory_hostname].ansible_distribution_major_version }}/luminoso-Signal-Desktop-fedora-{{ hostvars[inventory_hostname].ansible_distribution_major_version }}.repo
        dest: /etc/yum.repos.d/_copr_luminoso-Signal-Desktop.repo
        owner: root
        group: root
        mode: 0644

    - name: Install softwares
      dnf:
        name:
          - evolution-ews
          - feedreader
          - gedit-plugins
          - gimp
          - grisbi
          - inkscape
          - keepass
          - krita
          - libgnome-keyring
          - libreoffice
          - libreoffice-langpack-fr
          - nextcloud-client
          - qbittorrent
          - remmina
          - signal-desktop
          - transmission-remote-gtk

    - name: Install yubiko softwares
      dnf:
        name:
          - libu2f-host
          - libu2f-server
          - pam_yubico
          - pamu2fcfg
          - yubikey-personalization-gui
          - yubioath-desktop
        state: present
    - name: Fix sound on yoga
      copy:
        dest: "/etc/modprobe.d/disable_dmic.conf"
        content: "options snd_hda_intel dmic_detect=0"

    - name: Replace vi by vim
      block:
        - alternatives:
            name: vi
            link: /usr/local/bin/vi
            path: /usr/bin/vi
            priority: 100
        - alternatives:
            name: vi
            link: /usr/local/bin/vi
            path: /usr/bin/vim
            priority: 900

#    - name: Configure sensors
#      copy:
#        dest: "/etc/sensors.d/dell"
#        content: |
#          chip "dell_smm-virtual-0"
#            ignore temp4
#          chip "radeon-pci-0100"
#            ignore temp1

#    - name: Configure sudo
#     lineinfile:
#        dest: /etc/sudoers
#        state: present
#        regexp: '^%wheel'
#        line: '%wheel ALL=(ALL) ALL, NOPASSWD:/usr/bin/sed -i /nameserver 2001/d /etc/resolv.conf'
#        validate: 'visudo -cf %s'
