---
- hosts: localhost
  user: root
  tasks:
    - include_role:
        name: prerequisites
    - include_role:
        name: aria2
    - include_role:
        name: firefox
    - include_role:
        name: firefox
      vars:
        install_path: /opt/firefox-developer
        channel: devedition-latest
