---
- name: Install Mega.nz repo
  dnf:
    name: "https://mega.nz/linux/MEGAsync/Fedora_28/x86_64/megasync-Fedora_28.x86_64.rpm"
    state: present

- name: Install mega for desktop
  dnf:
    name: megasync
    state: present
