---
- name: Install Mega.nz repo
  dnf:
    name: "https://mega.nz/linux/MEGAsync/Fedora_{{ hostvars[inventory_hostname].ansible_distribution_major_version }}/x86_64/megasync-Fedora_{{ hostvars[inventory_hostname].ansible_distribution_major_version }}.x86_64.rpm"
    state: present

- name: Install mega for desktop
  dnf:
    name: megasync
    state: present
