---
- name: Install Development tools
  dnf:
    name: "@Development tools"
    state: present

- name: Install prerequisites
  dnf:
    name:
    - golang
    - kernel-headers
    - hugo

- name: Install Git
  dnf:
    name:
      - git
      - git-gui
      - gitg

- name: Setup VSCodium repo
  copy:
    src: vscodium.repo
    dest: /etc/yum.repos.d/vscodium.repo
    owner: root
    group: root
    mode: 0644

- name: Install VSCodium
  dnf:
    name: codium
