---
- name: Install virtualization softwares
  dnf:
    name: @Virtualization
    state: present

- name: Install virtio repository
  get_url:
    url: https://fedorapeople.org/groups/virt/virtio-win/virtio-win.repo
    dest: /etc/yum.repos.d/virtio-win.repo
    owner: root
    group: root
    mode: 0644

- name: Install virtio
  dnf:
    name: virtio-win
    state: present
