---
- name: Remove present versions
  dnf:
    name:
      - docker
      - docker-client
      - docker-client-latest
      - docker-common
      - docker-latest
      - docker-latest-logrotate
      - docker-logrotate
      - docker-selinux
      - docker-engine-selinux
      - docker-engine
    state: absent

- name: Install dependencies
  dnf:
    name: dnf-plugins-core
    state: present

- name: Add Docker repository
  get_url:
    url: https://download.docker.com/linux/fedora/docker-ce.repo
    dest: /etc/yum.repos.d/docker-ce.repo
    mode: 0644

- name: Install Docker
  dnf:
    name:
      - docker-ce
      - docker-compose
    state: present

- name: Start and enable Docker
  systemd:
    name: docker
    state: started
    enabled: yes
