---
- name: Install MariaDB server
  dnf:
    name: mariadb-server
    state: present

- name: Disable MariaDB service
  systemd:
    name: mariadb
    state: stopped
    enabled: no

- name: Create MariaDB data directory
  file:
    path: "{{ mariadb_data_dir }}"
    owner: mysql
    group: mysql
    state: directory

- name: Configure MariaDB
  lineinfile:
    path: /etc/my.cnf.d/mariadb-server.cnf
    regexp: 'datadir='
    line: "datadir={{ mariadb_data_dir }}"

- name: Configure SELinux for new MariaDB data directory
  sefcontext:
    target: "{{ mariadb_data_dir }}(/.*)?"
    setype: mysqld_db_t
    state: present

- name: Apply new SELinux file context to filesystem
  command: "restorecon -irv {{ mariadb_data_dir }}"

- name: Install httpd
  dnf:
    name:
      - httpd
      - httpd-itk
      - mod_ssl
    state: present

- name: Disable httpd service
  systemd:
    name: httpd
    state: stopped
    enabled: no

- name: Create httpd data directory
  file:
    path: "{{ httpd_data_dir }}"
    owner: apache
    group: apache
    state: directory

- name: Configure SELinux for new httpd data directory
  sefcontext:
    target: "{{ httpd_data_dir }}(/.*)?"
    setype: mysqld_db_t
    state: present

- name: Configure SELinux booleans
  seboolean:
    name: "{{ item.name }}"
    state: "{{ item.value }}"
    persistent: yes
  with_items:
    - {name: "httpd_can_network_connect", value: "yes"}
    - {name: "httpd_can_sendmail", value: "yes"}
    - {name: "httpd_execmem", value: "yes"}

- name: Apply new SELinux file context to filesystem
  command: "restorecon -irv {{ httpd_data_dir }}"

- name: Configure httpd
  template:
    src: httpd.conf.j2
    dest: /etc/httpd/conf/httpd.conf
    owner: root
    group: root
    mode: 0644

- name: Configure httpd itk module
  lineinfile:
    path: /etc/httpd/conf.modules.d/00-mpm-itk.conf
    regexp: 'LoadModule'
    line: 'LoadModule mpm_itk_module modules/mod_mpm_itk.so'

- name: Configure httpd vhosts
  template:
    src: "{{ item }}"
    dest: /etc/httpd/vhosts/{{ item | basename | regex_replace('\.j2','') }}
    owner: root
    group: root
  with_fileglob:
    - ../templates/vhosts/*.j2

- name: Use localhost certificate for all vhosts
  lineinfile:
    state: present
    insertafter: '^</VirtualHost>'
    line: |
      SSLCertificateFile /etc/pki/tls/certs/localhost.crt
      SSLCertificateKeyFile /etc/pki/tls/private/localhost.key

- name: Install php
  dnf:
    name:
      - ImageMagick
      - php
      - php-gd
      - php-imap
      - php-intl
      - php-mcrypt
      - php-mysqlnd
      - php-pecl-imagick
      - php-pecl-xdebug
      - php-symfony
    state: present

- name: Configure php
  lineinfile:
    path: /etc/php.ini
    regexp: '^date\.timezone ='
    line: 'date.timezone = Europe/Paris'

- name: Install phpMyAdmin
  dnf:
    name: phpMyAdmin
    state: present

- name: Generate blowfish secret for phpMyAdmin
  command: openssl rand -hex 32
  register: blowfish_secret

- name: Configure phpMyAdmin
  template:
    src: phpmyadmin.conf.j2
    dest: /etc/phpMyAdmin/config.inc.php
    owner: root
    group: apache
    mode: 0640

- name: Install postfix
  dnf:
    name: postfix
    state: present

- name: Configure postfix
  lineinfile:
    path: /etc/postfix/main.cf
    regexp: 'relayhost = '
    line: 'relayhost = {{ postfix_relay }}'

- name: Install composer
  dnf:
    name: composer
    state: present
