---
- name: Install aria2
  dnf:
    name: aria2
    state: present

- name: Copy service file
  template:
    src: aria2c.service.j2
    dest: /etc/systemd/system/aria2c.service
    owner: root
    group: root

- name: Create configuration directory
  file:
    path: "{{ config_dir }}"
    state: directory
    owner: "{{ running_user }}"
    group: "{{ running_user }}"
    recurse: yes

- name: Copy configuration file
  template:
    src: aria2.conf.j2
    dest: "{{ config_dir }}/aria2c.conf"
    owner: "{{ running_user }}"
    group: "{{ running_user }}"

- name: Start and enable service
  systemd:
    name: aria2c
    daemon_reload: yes
    enabled: yes
    state: started

- name: Remove old ariang
  command: '/usr/bin/podman rm -f aria_ng'

- name: Install ariang
  command: '/usr/bin/podman run -e ARIA_PROTOCOL=ws -p 8080:80 -d --name aria_ng remyj38/ariang:stable-alpine'

- name: Copy ariang service file
  copy:
    src: container_ariang.service
    dest: /etc/systemd/system/container_ariang.service
    owner: root
    group: root
    mode: 0755

- name: Enable ariang service
  systemd:
    name: container_ariang
    daemon_reload: yes
    enabled: yes
    state: started
